---

- hosts: all
  become: true
  tasks:
  
    - name: Update apt and install packages
      apt:
        pkg:
          - net-tools
        state: latest
        update_cache: true
        
    - name: "Update /etc/hosts"
      lineinfile:
        path: /etc/hosts
        line: '{{item.Host}}'
        state: present  
      with_items:
       - { Host: '192.168.70.130  k8s-master.vmware.local'}
       - { Host: '192.168.70.131  k8s-worker1.vmware.local'}
       - { Host: '192.168.70.132  k8s-worker2.vmware.local'}

    # Configure certificates
    - name: Check local certs directory exists
      file: state=directory path=/usr/local/share/ca-certificates

    - name: Install EasyRSA CA certificate
      copy: 
        src: files/certificates/ca.crt 
        dest: /usr/local/share/ca-certificates/EasyRSAca.crt

    - name: Update CA certificate index
      shell: /usr/sbin/update-ca-certificates

    - name: Check local certificate private key exists
      stat:
        path: "/etc/ssl/private/{{ inventory_hostname }}.pem"
      register: cert_private_key
    
    - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
      community.crypto.openssl_privatekey:
        path: "/etc/ssl/private/{{ inventory_hostname }}.pem"
      when: not cert_private_key.stat.exists

    - name: Create /etc/ssl/csr directory
      file: 
        state: directory
        path: /etc/ssl/csr

    - name: Check local certificate signing request exists
      stat:
        path: "/etc/ssl/csr/{{ inventory_hostname }}.req"
      register: cert_csr

    - name: Generate an OpenSSL Certificate Signing Request
      community.crypto.openssl_csr:
        path: "/etc/ssl/csr/{{ inventory_hostname }}.req"
        privatekey_path: "/etc/ssl/private/{{ inventory_hostname }}.pem"
        common_name: "{{ inventory_hostname }}"
      when: not cert_csr.stat.exists

    
 
