# This playbook prints a simple debug message
- hosts: webservers
  become: true
  tasks:
    - name: Update apt and install packages
      apt:
        pkg:
          - isc-dhcp-server
          - iptables-persistent
          - openvpn
          - unzip
        state: latest
        update_cache: true
